variables:
  TEMPLATE_VERSION: "v1"

delivery-pipeline:
  variables:
    PUSH_LATEST: "true"
  trigger:
    strategy: depend
    include:
      - project: "devops-pipelines/pipeline-triggers"
        ref: ${TEMPLATE_VERSION}
        file: "delivery.yaml"

.with-current-image:
  needs: [ "delivery-pipeline" ]
  image: ${APP_IMAGE}
  variables:
    APP_IMAGE_TAG: ${CI_COMMIT_SHORT_SHA}
    APP_IMAGE_SRC: ${BC_IMAGE_REPO}/${CI_PROJECT_PATH}
    APP_IMAGE: ${APP_IMAGE_SRC}:${APP_IMAGE_TAG}
    ARTIFACT_FOLDER: ".artifacts"
    GITLEAKS_REPORT: ${ARTIFACT_FOLDER}/gitleaks/gitleaks_report.json
    IMAGE_SBOM: ${ARTIFACT_FOLDER}/sbom/sbom.json
    COSIGN_EXPERIMENTAL: 1
  before_script:
    - mkdir ~/.docker && echo $BC_ARTIFACTORY_AUTH_JSON >> ~/.docker/config.json

grype-smoke-test:
  extends: .with-current-image
  services:
    - name: artifactory.cloud.cms.gov/batcave-docker/devops-pipelines/pipeline-tools/grype-cache-server:latest
      alias: vul-server
  script:
    - curl -LO vul-server/vulndb.tar.gz
    - grype db import vulndb.tar.gz
    - grype db check
    - grype bkimminich/juice-shop -o json --file report.json
    - cat report.json | jq .

syft-smoke-test:
  extends: .with-current-image
  script:
    - syft version
    - syft artifactory.cloud.cms.gov/docker/alpine:latest --scope=AllLayers -o cyclonedx-json --file ${IMAGE_SBOM}
    - cat ${IMAGE_SBOM}

juice-shop-clone:
  image: artifactory.cloud.cms.gov/docker/alpine/git:latest
  artifacts:
    expire_in: "1 day"
    paths:
      - "juice-shop"
  script:
    - git config --global --add safe.directory *
    - git clone https://github.com/juice-shop/juice-shop.git

gitleaks-smoke-test:
  extends: .with-current-image
  needs: [ "delivery-pipeline", "juice-shop-clone" ]
  script:
    - mkdir -p $ARTIFACT_FOLDER/gitleaks
    - touch ${GITLEAKS_REPORT}
    - echo "Starting Gitleaks Secrets Scan"
    - gitleaks detect --exit-code 0 --verbose --source juice-shop --report-format json --report-path ${GITLEAKS_REPORT}

cosign-crane-smoke-test:
  extends: .with-current-image
  script:
    - cosign version
    - crane version
    - export TARGET_IMAGE=$(crane digest --full-ref ${APP_IMAGE})
    - echo "Application Image Digest -> ${TARGET_IMAGE}"
    - echo "Signing image using cosign with OIDC token"
    - cosign sign --identity-token=$(cat /var/run/secrets/eks.amazonaws.com/serviceaccount/token) ${TARGET_IMAGE}

gatecheck-smoke-test:
  extends: .with-current-image
  script:
    - gatecheck version
    - gatecheck config info

release-tool-smoke-test:
  extends: .with-current-image
  script:
    - release-cli help

release-pipeline:
  trigger:
    strategy: depend
    include:
      - project: "devops-pipelines/pipeline-triggers"
        ref: ${TEMPLATE_VERSION}
        file: "release.yaml"
  rules:
    - if: $CI_COMMIT_TAG
