name: release

on:
  push:
    # run only against tags
    tags:
      - "*"

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set outputs
        id: vars
        run: |
          echo "tag_name=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT 
      - run: |
          docker buildx imagetools create \
            --tag ghcr.io/cms-enterprise/batcave/omnibus:${{ github.ref_name }} \
            ghcr.io/cms-enterprise/batcave/omnibus:${{ steps.vars.outputs.tag_name }}

      - run: |
          gh release create ${{ github.ref_name }} --generate-notes
